### ISSUE TITLE
Replicating a table after all nodes have joined

### ISSUE THREAD

**Issue by amitlan** [citusdata/pg_paxos#11]
What I was trying to do is this:
- Created a group and didn't yet replicate a table
- Joined server 2 to the group
- Went back to server 1 and replicated a table
- Back to server 2, created the same table and inserted a row in it
- Back at server 1 looking for the row - don't find it
- Perhaps failed to get the sequence right; tried using a different group (making sure to replicate the table before joining server 2)
- Could create the new group but couldn't replicate table because:

```
ERROR:  duplicate key value violates unique constraint "replicated_tables_pkey"
```

How to go about replicating a table after all nodes have joined?

By the way, I didn't find the tear-down/drop counterpart of `paxos_create_group()`.  Is that a TODO?

**Comment by marcocitus** [comment]
The documentation isn't super clear on this, but you need to call paxos_replicate_table after creating the table on server 2 to activate replication on that table. The call to paxos_replicate_table is not itself logged in the Paxos group. Doing so would be technically possible, but probably a bad idea, since it would mean that pg_paxos would have to make round-trips even when querying regular tables on the off-chance that someone else in the group marked the table as replicated. Calling paxos_replicate_table also does not ensure that the tables have the same initial contents. Conversely, paxos_join_group automatically copies the replicated tables and their contents from the existing node.

There is no paxos_drop_group at the moment. I'm not sure what the semantics of that function would be, but I could see paxos_leave_group being useful, so I've added it on the develop branch. You can use it as:

```
SELECT paxos_leave_group('group id');
```

It cleanly removes the node on which you call it from the group, stops replication, and leaves the table in a state that was consistent when paxos_leave_group was called.

There's no upgrade script yet, so you'll have to drop+create extension to use it.

**Comment by amitlan** [comment]
Ah, thanks for explaining.  I will try that.
