### ISSUE TITLE
use of function only updates node where function is called

### ISSUE THREAD

**Issue by Slania** [citusdata/pg_paxos#7]
<img width="1404" alt="functions don t work" src="https://cloud.githubusercontent.com/assets/855842/13381183/cc2889ce-de1a-11e5-8ad5-63af76e41e3c.png">

As you can see, simple table with an insert function. Only applies the function to the node I called the function from. Also, it doesn't matter if the other node has the function or not. I understand this might be because of no support for distributed transactions and that functions are inherently transactional but there is no warning or error message for the same.

**Comment by marcocitus** [comment]
This is currently addressed in the develop branch (version 0.2):
https://github.com/citusdata/pg_paxos/tree/develop

Instead of logging the literal query string, this version deparses the query plan, which gives it the query as it is meant to be executed after evaluating parameters. However, since the deparser (from ruleutils.c in postgres) doesn't deparse all query plans correctly, this version breaks some other (complex) queries.
